// הטקסטים של בוט הוואטסאפ, בעברית ובאנגלית (שמות אולמות, ערים ושכונות נשארים כפי שהם בטבלה).
// כותרות כפתורים - עד 20 תווים; כותרות שורות ברשימה - עד 24.
export const T = {
  he: {
    welcome: '*מזל טוב* 🤍\nאני בוט *שמחה בשיחה* ואעזור לך למצוא בקלות אולם מתאים לאירוע!',
    menuBody: 'יש לבחור אחת מהאפשרויות 😊', menuButton: 'לבחירה',
    searchDesc: 'לפי כמות מוזמנים, עיר ושכונה', byNameDesc: 'שם אולם או בית כנסת',
    search: 'חיפוש כללי', byName: 'חיפוש לפי שם', more: 'עוד אפשרויות',
    moreBody: 'עוד אפשרויות', moreButton: 'בחירה',
    owner: 'להוספת אולם', lang: 'English', back: 'תפריט ראשי',
    askGuests: 'מה כמות המוזמנים המשוערת? (יש לכתוב מספר 🔢)',
    badGuests: 'לא הבנתי את המספר.\nיש לכתוב כמות מוזמנים, למשל 250',
    askCity: 'באיזו עיר? כתבו את שם העיר או בחרו מהרשימה ☺️',
    cityButton: 'בחירת עיר', cityNone: (c) => `לא נמצאו אולמות ב${c}`,
    moreCities: 'עוד ערים ←', moreHoods: 'עוד שכונות ←', moreHalls: 'עוד אולמות ←',
    askHood: 'באיזו שכונה? אפשר לכתוב שם שכונה, או לבחור:',
    pickHood: 'בחירת שכונה', allCity: 'כל העיר', hoodButton: 'בחירת שכונה',
    hoodNone: (h) => `לא נמצאו אולמות בשכונת ${h}`,
    extraHalls: 'אולמות נוספים בעיר',
    askFree: 'כתבו את שם האולם והעיר, למשל:\n*היכל שמחה בירושלים*',
    askHall: 'כתבו את שם האולם או בית הכנסת',
    hallList: 'רשימת אולמות', hallNone: (n) => `לא נמצא אולם בשם ${n}`,
    pickHall: 'באיזה אולם?', hallButton: 'בחירת אולם',
    tryAgain: 'נסיון נוסף',
    found1: 'נמצא אולם אחד', foundN: (n) => `נמצאו ${n} אולמות`,
    upTo: (n) => `עד ${n} אורחים`, hoodWord: 'שכונת', synagogue: 'בית הכנסת',
    next: 'מה הלאה?', nextButton: 'אפשרויות',
    rMore: 'עוד אולמות', rNear: 'אולמות בגודל קרוב', rHood: 'חיפוש בשכונה אחרת', rGuests: 'שינוי כמות מוזמנים',
    noFit: (where, g) => `לא נמצאו אולמות ${where} המתאימים ל-${g} מוזמנים`,
    larger: 'אולמות גדולים יותר', smaller: 'אולמות קטנים יותר', changeGuests: 'שינוי כמות',
    noResults: (city, g) => `לא נמצאו אולמות ב${city} עבור ${g} מוזמנים`, changeCity: 'שינוי עיר',
    inCity: (c) => `ב${c}`, inHood: (h) => `בשכונת ${h}`,
    howToCall: (num, ext) => `📞 *לחיוג לאולם:* התקשרו ${num ? `למספר ${num}` : 'למספר הזה'}, הקישו *2*, *${ext}*, *ו-#*.`,
    dialPage: '📲 או לחצו על הקישור',
    ownerInfo: (num, link) => ['להוספת אולם למערכת, נשמח אם תשלחו מייל לכתובת:', 'simchabesicha@gmail.com', 'רשמו את שם האולם,', 'מספר פלאפון להזמנה,', 'כמות אורחים מקסימלית,', 'שכונה וכתובת מדויקת.',
      `אם ברצונכם להשאיר הודעה קולית התקשרו למספר ${num || 'הזה'} והקישו 5${link ? `, או לחצו על הקישור: ${link}` : '.'}`].join('\n'),
    unknown: 'לא הבנתי. אפשר לבחור מהכפתורים, או לכתוב "תפריט".',
    menuHint: '(לחזרה לתפריט כתבו "תפריט")',
  },
  en: {
    welcome: '*Mazal Tov* 🤍\nI am the *Simcha BeSicha* bot, and I will help you easily find the right hall for your event!',
    menuBody: 'Please choose one of the options 😊', menuButton: 'Choose',
    searchDesc: 'By guests, city and neighborhood', byNameDesc: 'Hall or synagogue name',
    search: 'General search', byName: 'Search by name', more: 'More options',
    moreBody: 'More options', moreButton: 'Choose',
    owner: 'Add a hall', lang: 'עברית', back: 'Main menu',
    askGuests: 'What is the estimated number of guests? (please type a number 🔢)',
    badGuests: "I didn't get the number.\nPlease type the guest count, e.g. 250",
    askCity: 'Which city? Type the city name or choose from the list ☺️',
    cityButton: 'Choose city', cityNone: (c) => `No halls found in ${c}`,
    moreCities: 'More cities ←', moreHoods: 'More neighborhoods ←', moreHalls: 'More halls ←',
    askHood: 'Which neighborhood? Type a name, or choose:',
    pickHood: 'Choose neighborhood', allCity: 'Whole city', hoodButton: 'Choose',
    hoodNone: (h) => `No halls found in ${h}`,
    extraHalls: 'More halls in the city',
    askFree: 'Type the hall name and the city (city in Hebrew), for example:\n*היכל שמחה בירושלים*',
    askHall: 'Type the hall name or synagogue name',
    hallList: 'Hall list', hallNone: (n) => `No hall found named ${n}`,
    pickHall: 'Which hall?', hallButton: 'Choose hall',
    tryAgain: 'Try again',
    found1: 'Found one hall', foundN: (n) => `Found ${n} halls`,
    upTo: (n) => `up to ${n} guests`, hoodWord: 'neighborhood', synagogue: 'synagogue',
    next: 'What next?', nextButton: 'Options',
    rMore: 'More halls', rNear: 'Halls of similar size', rHood: 'Another neighborhood', rGuests: 'Change guest count',
    noFit: (where, g) => `No halls ${where} fit ${g} guests`,
    larger: 'Larger halls', smaller: 'Smaller halls', changeGuests: 'Change guests',
    noResults: (city, g) => `No halls in ${city} for ${g} guests`, changeCity: 'Change city',
    inCity: (c) => `in ${c}`, inHood: (h) => `in ${h}`,
    howToCall: (num, ext) => `📞 *To call the hall:* call ${num ? num : 'this number'}, press *2*, *${ext}*, then *#*.`,
    dialPage: '📲 Or tap the link',
    ownerInfo: (num, link) => ['To add your hall to the system, please send an email to:', 'simchabesicha@gmail.com', 'and include the hall name,', 'a phone number for bookings,', 'the maximum number of guests,', 'the neighborhood and the exact address.',
      `To leave a voice message, call ${num || 'this number'} and press 5${link ? `, or tap the link: ${link}` : '.'}`].join('\n'),
    unknown: 'I did not understand. Choose a button, or type "menu".',
    menuHint: '(to return to the menu type "menu")',
  },
};
