// הטקסטים של בוט הוואטסאפ, בעברית ובאנגלית (שמות אולמות, ערים ושכונות נשארים כפי שהם בטבלה).
// כותרות כפתורים - עד 20 תווים; כותרות שורות ברשימה - עד 24.
export const T = {
  he: {
    welcome: '👋 ברוכים הבאים ל*שמחה בשיחה* - חיפוש אולם אירועים.',
    menuBody: 'מה תרצו לעשות?', menuButton: 'לבחירה',
    searchDesc: 'לפי כמות מוזמנים, עיר ושכונה', byNameDesc: 'שם אולם או בית כנסת', extDesc: 'כתבו מספר שלוחה',
    search: 'חיפוש לפי מוזמנים', byName: 'חיפוש לפי שם', more: 'עוד אפשרויות',
    moreBody: 'עוד אפשרויות', moreButton: 'בחירה',
    ext: 'יש לי מספר שלוחה', owner: 'להוספת אולם', lang: 'English', back: 'תפריט ראשי',
    askGuests: 'כמה מוזמנים משוערים? (כתבו מספר)',
    badGuests: 'לא הבנתי את המספר. כתבו כמות מוזמנים, למשל 250',
    askCity: 'באיזו עיר? בחרו מהרשימה או כתבו את שם העיר',
    cityButton: 'בחירת עיר', cityNone: (c) => `לא נמצאו אולמות ב${c}`,
    moreCities: 'עוד ערים ←', moreHoods: 'עוד שכונות ←', moreHalls: 'עוד אולמות ←',
    askHood: 'באיזו שכונה? אפשר לכתוב שם שכונה, או לבחור:',
    pickHood: 'בחירת שכונה', allCity: 'כל העיר', hoodButton: 'בחירת שכונה',
    hoodNone: (h) => `לא נמצאו אולמות בשכונת ${h}`,
    extraHalls: 'אולמות נוספים בעיר',
    askExt: 'כתבו את מספר השלוחה של האולם',
    extNone: (e) => `שלוחה ${e} לא קיימת`,
    askHall: 'כתבו את שם האולם או בית הכנסת',
    hallList: 'רשימת אולמות', hallNone: (n) => `לא נמצא אולם בשם ${n}`,
    pickHall: 'באיזה אולם?', hallButton: 'בחירת אולם',
    tryAgain: 'נסיון נוסף',
    found1: 'נמצא אולם אחד', foundN: (n) => `נמצאו ${n} אולמות`,
    upTo: (n) => `עד ${n} אורחים`, hoodWord: 'שכונת', synagogue: 'בית הכנסת',
    extWord: 'שלוחה',
    next: 'מה הלאה?', nextButton: 'אפשרויות',
    rMore: 'עוד אולמות', rNear: 'אולמות בגודל קרוב', rHood: 'חיפוש בשכונה אחרת', rGuests: 'שינוי כמות מוזמנים',
    noFit: (where, g) => `לא נמצאו אולמות ${where} המתאימים ל-${g} מוזמנים`,
    larger: 'אולמות גדולים יותר', smaller: 'אולמות קטנים יותר', changeGuests: 'שינוי כמות',
    noResults: (city, g) => `לא נמצאו אולמות ב${city} עבור ${g} מוזמנים`, changeCity: 'שינוי עיר',
    inCity: (c) => `ב${c}`, inHood: (h) => `בשכונת ${h}`,
    howToCall: (num, ext) => `📞 *לחיוג לאולם:* התקשרו ${num ? `למספר ${num}` : 'למספר הזה'}, הקישו *2*, אחר כך את מספר השלוחה${ext ? ` *${ext}*` : ''} ואז *סולמית (#)*.`,
    callAll: (num) => `📞 *לחיוג לאולם:* התקשרו ${num ? `למספר ${num}` : 'למספר הזה'}, הקישו *2*, אחר כך את מספר השלוחה שמופיע ליד האולם ואז *סולמית (#)*.`,
    ownerInfo: 'להוספת האולם למערכת שלחו מייל לכתובת:\nSimchabesicha@gmail.com\nוכתבו שם האולם, מספר פלאפון להזמנה, שכונה וכתובת מדויקת.',
    unknown: 'לא הבנתי. אפשר לבחור מהכפתורים, או לכתוב "תפריט".',
    menuHint: '(לחזרה לתפריט כתבו "תפריט")',
  },
  en: {
    welcome: '👋 Welcome to *Simcha BeSicha* - find an event hall.',
    menuBody: 'What would you like to do?', menuButton: 'Choose',
    searchDesc: 'By guests, city and neighborhood', byNameDesc: 'Hall or synagogue name', extDesc: 'Type an extension',
    search: 'Search by guests', byName: 'Search by name', more: 'More options',
    moreBody: 'More options', moreButton: 'Choose',
    ext: 'I have an extension', owner: 'Add a hall', lang: 'עברית', back: 'Main menu',
    askGuests: 'About how many guests? (type a number)',
    badGuests: "I didn't get the number. Type the guest count, e.g. 250",
    askCity: 'Which city? Choose from the list or type the city name',
    cityButton: 'Choose city', cityNone: (c) => `No halls found in ${c}`,
    moreCities: 'More cities ←', moreHoods: 'More neighborhoods ←', moreHalls: 'More halls ←',
    askHood: 'Which neighborhood? Type a name, or choose:',
    pickHood: 'Choose neighborhood', allCity: 'Whole city', hoodButton: 'Choose',
    hoodNone: (h) => `No halls found in ${h}`,
    extraHalls: 'More halls in the city',
    askExt: "Type the hall's extension number",
    extNone: (e) => `Extension ${e} does not exist`,
    askHall: 'Type the hall name or synagogue name',
    hallList: 'Hall list', hallNone: (n) => `No hall found named ${n}`,
    pickHall: 'Which hall?', hallButton: 'Choose hall',
    tryAgain: 'Try again',
    found1: 'Found one hall', foundN: (n) => `Found ${n} halls`,
    upTo: (n) => `up to ${n} guests`, hoodWord: 'neighborhood', synagogue: 'synagogue',
    extWord: 'Ext.',
    next: 'What next?', nextButton: 'Options',
    rMore: 'More halls', rNear: 'Halls of similar size', rHood: 'Another neighborhood', rGuests: 'Change guest count',
    noFit: (where, g) => `No halls ${where} fit ${g} guests`,
    larger: 'Larger halls', smaller: 'Smaller halls', changeGuests: 'Change guests',
    noResults: (city, g) => `No halls in ${city} for ${g} guests`, changeCity: 'Change city',
    inCity: (c) => `in ${c}`, inHood: (h) => `in ${h}`,
    howToCall: (num, ext) => `📞 *To call the hall:* call ${num ? num : 'this number'}, press *2*, then the extension${ext ? ` *${ext}*` : ''} and then *# (pound)*.`,
    callAll: (num) => `📞 *To call a hall:* call ${num ? num : 'this number'}, press *2*, then the extension shown next to the hall and then *# (pound)*.`,
    ownerInfo: 'To add your hall, email:\nSimchabesicha@gmail.com\nwith the hall name, a phone number for bookings, the neighborhood and the exact address.',
    unknown: 'I did not understand. Choose a button, or type "menu".',
    menuHint: '(to return to the menu type "menu")',
  },
};
